Fix Doxygen on Windows runner

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -43,8 +43,13 @@ jobs:
           if (-not (Get-Command miktexsetup -ErrorAction SilentlyContinue)) {
             choco install miktex --no-progress -y
           }
+          echo "$env:PATH" | Select-String 'MiKTeX' || echo 'MiKTeX not found in PATH.'
+          $registeredPath = (Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\miktexsetup.exe' -ErrorAction SilentlyContinue).GetValue('')
+          if (-not $registeredPath) {
+            echo 'MiKTeX not found in registry.'
+          }
           $miktexBin = 'C:\Program Files\MiKTeX\miktex\bin\x64'
-          refreshenv
+          $env:PATH = "$miktexBin;$env:PATH"
           miktexsetup finish
           miktex-console --package-install epstopdf --yes
 
